package shadows.android.shadowswalker.dao.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import shadows.android.shadowswalker.db.MessageInfo;

import shadows.android.shadowswalker.dao.green.MessageInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageInfoDaoConfig;

    private final MessageInfoDao messageInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);

        registerDao(MessageInfo.class, messageInfoDao);
    }
    
    public void clear() {
        messageInfoDaoConfig.clearIdentityScope();
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

}
